spring.application.name=api
# Configuración de Servidor
server.port=8080

# Conexión a Base de Datos (Docker Network)
spring.datasource.url=jdbc:postgresql://db:5432/automotriz_db
spring.datasource.username=user_admin
spring.datasource.password=secret_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
